### ISSUE TITLE
NOTHING BUT THE WORD "BUG"

### ISSUE THREAD

**Issue by USER-OF-SOFTWARE** [GITHUB-DEVELOPER-ACCOUNT/REPOSITORY-NAMED-AFTER-A-PORTMANTEAU-BETWEEN-A-SERVICE-NAME-AND-A-LANGUAGE-NAME#3]
ENTIRE LOG FILE PASTED INTO THE DESCRIPTION BOX WITHOUT USING A CODE BLOCK WITH THE EXPECTATION THAT THE BUG THAT IS AN INTENDED FEATURE WILL BE FIXED

**Comment by GITHUB-DEVELOPER-ACCOUNT** [comment]
A COMMENT STATING THAT THE ISSUE DESCRIBED SHARES THE CAUSE OF ANOTHER ISSUE ALREADY BEEN RAISED BY THE SAME USER, REFERENCING THE NUMBER OF THE ISSUE IN QUESTION, AND STATING THAT THE ISSUE WILL BE SOLVED AS SOON A POSSIBLE
