### ISSUE TITLE
QUESTION PERTAINING TO THE ACTIVITY OF THIS GITHUB REPOSITORY

### ISSUE THREAD

**Issue by USER-OF-SOFTWARE** [GITHUB-DEVELOPER-ACCOUNT/REPOSITORY-NAMED-AFTER-A-PORTMANTEAU-BETWEEN-A-SERVICE-NAME-AND-A-LANGUAGE-NAME#5]
LONGER QUESTION ASKING WHETHER THIS PROJECT IS AN ABANDONED OR DEAD STATE.

**Comment by GITHUB-DEVELOPER-ACCOUNT** [comment]
A COMMENT STATING THAT THE REPOSITORY IS IN ACTIVE DEVELOPMENT AND NOT ABANDONED, INVITING THE ISSUE AUTHOR TO CONTRIBUTE
